.idea/gradle.xml
.idea/misc.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/myapplication/BeginningActivity.kt
app/src/main/java/com/example/myapplication/LoginActivity.kt
app/src/main/java/com/example/myapplication/SignupActivity.kt
app/src/main/res/drawable/background_1.xml
app/src/main/res/drawable/background_2.xml
app/src/main/res/drawable/gradient_list.xml
app/src/main/res/drawable/sign_in_rectangle.xml
app/src/main/res/drawable/sign_up_rectangle.xml
app/src/main/res/layout/activity_beginning.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_signup.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

Brian-Beginning-Buttons

---

.idea/deploymentTargetDropDown.xml
app/google-services.json
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/myapplication/BeginningActivity.kt
app/src/main/res/layout/activity_login.xml

Adding button functionality to allow other collaborators to work with

Buttons are functional

---

.idea/deploymentTargetDropDown.xml
app/src/main/java/com/example/myapplication/MainActivitySignup.kt
app/src/main/res/layout/activity_login.xml

Daniel brian activity login

---

app/src/main/java/com/example/myapplication/BeginningActivity.kt

test connection to repo after transfer to Organization

---

.idea/misc.xml
.idea/vcs.xml
app/src/main/java/com/example/myapplication/BeginningActivity.kt

Test chat 

---

.idea/.gitignore
.idea/misc.xml
.idea/vcs.xml
app/src/main/res/drawable/bold_border.xml
app/src/main/res/layout/intro_descriptioin.xml
app/src/main/res/values/strings.xml

Implemented an intro description page and added variables in drawable folder.

Created Description Input Page

---

.idea/.name
.idea/appInsightsSettings.xml
.idea/misc.xml
.idea/vcs.xml
app/build.gradle.kts
app/src/main/java/com/example/myapplication/LoginActivity.kt
app/src/main/res/layout/activity_login.xml

Firebase Login
https://github.com/InterMeetiate/Intermeet/assets/88005420/48bc8f78-de51-4d4e-93e8-897eebb62e10
**To test:**
intermeet@test.com
password

Firebase Login

---

.idea/deploymentTargetDropDown.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/myapplication/AgeFragment.kt
app/src/main/java/com/example/myapplication/DistanceFragment.kt
app/src/main/java/com/example/myapplication/OccupationFragment.kt
app/src/main/java/com/example/myapplication/PreferenceActivity.kt
app/src/main/java/com/example/myapplication/PronounFragment.kt
app/src/main/java/com/example/myapplication/SharedViewModel.kt
app/src/main/java/com/example/myapplication/TagsFragments.kt
app/src/main/java/com/example/myapplication/UserInfoActivity.kt
app/src/main/res/drawable/tag_background.xml
app/src/main/res/layout/activity_preference.xml
app/src/main/res/layout/activity_user_info.xml
app/src/main/res/layout/fragment_age.xml
app/src/main/res/layout/fragment_distance.xml
app/src/main/res/layout/fragment_occupation.xml
app/src/main/res/layout/fragment_pronoun.xml
app/src/main/res/layout/fragment_tags_fragments.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml

FINALLY fixed the merge conflict with my code and the org code after merging with Sean's code

Finished User profile and Preference

---

.idea/deploymentTargetDropDown.xml
.idea/discord.xml
.idea/misc.xml
app/src/main/java/com/example/myapplication/BirthdayActivity.kt
app/src/main/java/com/example/myapplication/PasswordActivity.kt
app/src/main/java/com/example/myapplication/PhotoUploadActivity.kt
app/src/main/java/com/example/myapplication/SchoolActivity.kt

Almost connecting all signup pages

Added button func to 2/3s of the sign up

---

.idea/deploymentTargetDropDown.xml
app/google-services.json

Modified google services to work with Android app deployment.

Android App Deployment

---

app/src/main/res/layout/activity_location.xml
app/src/main/res/layout/activity_notification.xml
app/src/main/res/layout/activity_photo_upload.xml
app/src/main/res/layout/intro_descriptioin.xml
app/src/main/res/values/strings.xml

Spelling error for Preference page.
Fixed text bot clipping onto the edge of the phone for intro_description.xml 
Made the "NEXT" text visible for the Photos page
Adjusted the layout of Notification and Location pages to be more in line.

Fixed various bugs

---

app/src/main/res/layout/activity_main.xml

Added the top bar to the discover page

Top bar addition

---

.idea/discord.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/intermeet/android/AccountCreationActivity.kt
app/src/main/res/layout/activity_preference.xml

Use this to sign in:
email: test123@gmail.com
pass: test123

Updated sign in and up processs to go to main activity

---

app/src/main/res/layout/activity_main.xml

Reverts InterMeetiate/Intermeet#57
This man didn't do it right

Revert "Top bar addition"

---

app/src/main/java/com/intermeet/android/AutoCompleteAdapter.kt
app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/res/layout/activity_events.xml
app/src/main/res/values/dimens.xml

Implemented Auto-suggestions for address and place searching through Places API and modified UI implementation for Events page.

Events branch

---

.idea/misc.xml
app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/res/layout/activity_events.xml

Made it so that the event bottom sheet can't be completely hidden when dragged down.

Fixed event bottom sheet

---

app/src/main/java/com/intermeet/android/DiscoverFragment.kt
app/src/main/java/com/intermeet/android/DiscoverViewModel.kt
app/src/main/java/com/intermeet/android/IntermeetApp.kt
app/src/main/java/com/intermeet/android/UsersPagerAdapter.kt
app/src/main/res/layout/fragment_discover.xml
app/src/main/res/values/strings.xml

Added likes, seen so users dont see the same, added refresh for said component. currently testing with 
locationtest6@test.com
test123

Discover likes

---

app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/res/drawable/map_icon.xml
app/src/main/res/drawable/my_location.xml
app/src/main/res/layout/activity_events.xml

- Map now starts at current user's location
- Added two new buttons to help with user manipulation of the map

Added more features to the map

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/intermeet/android/HelpCenterActivity.kt
app/src/main/java/com/intermeet/android/ProfileFragment.kt
app/src/main/res/drawable/line_border.xml
app/src/main/res/layout/activity_help_center.xml
app/src/main/res/values/strings.xml

Help center

---

.idea/appInsightsSettings.xml
.idea/deploymentTargetDropDown.xml
.idea/vcs.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/intermeet/android/DiscoverActivity.kt
app/src/main/java/com/intermeet/android/LikesPageFragment.kt
app/src/main/java/com/intermeet/android/MainActivity.kt
app/src/main/java/com/intermeet/android/ProfileActivity.kt
app/src/main/java/com/intermeet/android/RecyclerData.kt
app/src/main/java/com/intermeet/android/RecyclerViewAdapter.kt
app/src/main/res/layout/card_layout.xml
app/src/main/res/layout/fragment_likespage.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Reverts InterMeetiate/Intermeet#81

Revert "Revert "Lieks page addition""

---

app/src/main/java/com/intermeet/android/Event.kt
app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/res/layout/event_details_card.xml

The going button successfully adds the user to the list of people who are going.

Events Page Going button

---

app/src/main/java/com/intermeet/android/EditPreference.kt
app/src/main/java/com/intermeet/android/LikesDetailFragment.kt

I am tired of Laptop Android Studio and PC Android Studio having different intelligence when recognizing files so I just put the function to calculate age in the file itself

Fixing this shiet cause Android Studio is shiet at recognizing files

---

.idea/misc.xml
app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/java/com/intermeet/android/UserAdapter.kt
app/src/main/res/layout/activity_events.xml
app/src/main/res/layout/event_details_card.xml
app/src/main/res/layout/user_list_item.xml
app/src/main/res/layout/users_list_dialog.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Added a bunch of features to the events page
- Clicking on the "Going (x)" text will show a list of users who are going to an event
- A loading screen will now appear while the map is still getting ready
- Revamped and fixed the UI of the event card to look better
- A preview of users who are going to that event will be shown on the event card itself

Events - New Features

---

app/src/main/java/com/intermeet/android/InterestsAdapter.kt
app/src/main/java/com/intermeet/android/UserDetailFragment.kt
app/src/main/res/drawable/interest_background.xml
app/src/main/res/layout/fragment_user_detail.xml
app/src/main/res/layout/item_interest.xml

Added interest for user display

Add in interests for user display

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/intermeet/android/ChatActivity.kt
app/src/main/java/com/intermeet/android/ChatAdapter.kt
app/src/main/java/com/intermeet/android/ChatFragment.kt
app/src/main/java/com/intermeet/android/MainActivity.kt
app/src/main/java/com/intermeet/android/Message.kt
app/src/main/java/com/intermeet/android/MessageAdapter.kt
app/src/main/res/layout/activity_chat.xml
app/src/main/res/layout/chat_users.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/receive.xml
app/src/main/res/layout/sent.xml
app/src/main/res/values/strings.xml

- Added real-time messaging between two users.
- A few other minor UI changes.

Chats Page Functionality

---

app/build.gradle.kts
app/google-services.json
app/src/main/AndroidManifest.xml
app/src/main/java/com/intermeet/android/DiscoverViewModel.kt
app/src/main/java/com/intermeet/android/IntermeetApp.kt
app/src/main/java/com/intermeet/android/MainActivity.kt
app/src/main/java/com/intermeet/android/MyFirebaseMessagingService.kt
app/src/main/res/values/strings.xml
build.gradle.kts

1. The underlying trigger for notifications is by the NEW addition of a user getting a like. So if the user is already liked by the current user and you press the like button again, it wont work. Need to delete "likes" object in Realtime Database
2. Need to enable notifications to work

Notification match

---

app/src/main/java/com/intermeet/android/NotificationActivity.kt

If notifications are already enabled it will skip to the photo activity

Prompt the user to enable notification now

---

app/src/main/java/com/intermeet/android/ChatActivity.kt
app/src/main/java/com/intermeet/android/ChatFragment.kt
app/src/main/java/com/intermeet/android/IntermeetApp.kt
app/src/main/java/com/intermeet/android/MainActivity.kt
app/src/main/java/com/intermeet/android/MyFirebaseMessagingService.kt
app/src/main/res/values/strings.xml

Notifications for chats is fully implemented

Notification chat

---

app/src/main/java/com/intermeet/android/AccountCreationActivity.kt
app/src/main/java/com/intermeet/android/SettingsActivity.kt
app/src/main/res/layout/activity_account_creation.xml

Added a loading screen for the AccountCreation while it registers the user to our firebase and added a FirebaseAuth logout

AccountCreation Loading Screen and Proper Logout

---

app/src/main/res/layout/activity_beginning.xml
build.gradle.kts

Fixed spacing with message in BeginningActivity and build.gradle version

Fixed errors

---

app/build.gradle.kts
app/src/main/java/com/intermeet/android/ChatActivity.kt
app/src/main/java/com/intermeet/android/ChatAdapter.kt
app/src/main/java/com/intermeet/android/Hangout.kt
app/src/main/java/com/intermeet/android/HangoutAdapter.kt
app/src/main/res/drawable/hangout_bg.xml
app/src/main/res/drawable/hangout_dot.xml
app/src/main/res/drawable/more_options_icon.xml
app/src/main/res/layout/calendar_day_layout.xml
app/src/main/res/layout/calendar_day_title_text.xml
app/src/main/res/layout/calendar_day_titles_container.xml
app/src/main/res/layout/calendar_view.xml
app/src/main/res/layout/hangout_view.xml

Implemented custom CalendarView for better functionality and UI.

Custom CalendarView

---

app/src/main/java/com/intermeet/android/EventsFragment.kt

No participant text now disappears when populated.

Events Tab Fix

---

app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/res/layout/activity_events.xml

- If a user is already going to an event, the button changes so that they can't press it anymore.
- Made the map change button and the navigate to user button smaller and have the gradient as a background.
- Fixed sorting events by distance.

Events Page Touch up

---

app/src/main/java/com/intermeet/android/ChatActivity.kt
app/src/main/java/com/intermeet/android/EditPreference.kt
app/src/main/java/com/intermeet/android/LikesPageFragment.kt
app/src/main/java/com/intermeet/android/MainActivity.kt
app/src/main/java/com/intermeet/android/MyFirebaseMessagingService.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_discover.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_userdetails_cardstack.xml

Istg if any other code breaks the notification then imma kms

Latest Notification Fix

---

app/src/main/java/com/intermeet/android/DiscoverViewModel.kt

Edited filter to include already liked profiles

Add filter for likes

---

app/src/main/java/com/intermeet/android/CardStackAdapter.kt
app/src/main/java/com/intermeet/android/LikesFragment.kt
app/src/main/res/layout/fragment_user_detail.xml

User's exact coordinates aren't revealed anymore. It instead displays "{City}, {State}" now.

CardStackView Fix

---

app/src/main/java/com/intermeet/android/EmailGrabActivity.kt
app/src/main/res/layout/activity_events.xml
app/src/main/res/layout/forgot_password.xml
app/src/main/res/layout/fragment_discover.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_user_detail.xml
app/src/main/res/layout/reset_password.xml

Fixed events and profiles margin.

Fix margins

---

app/src/main/java/com/intermeet/android/EventsFragment.kt

Pressing the going button no longer crashes the app

Fix events page

---

app/build.gradle.kts
app/proguard-rules.pro
app/src/main/java/com/intermeet/android/DiscoverViewModel.kt
app/src/main/java/com/intermeet/android/LikesFragment.kt
app/src/main/java/com/intermeet/android/PassAnimation.kt
app/src/main/res/layout/fragment_likes_prepage.xml

Pass Animation done for Like page

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/intermeet/android/EventsFragment.kt
app/src/main/java/com/intermeet/android/LoginActivity.kt
app/src/main/res/drawable/custom_cursor.xml
app/src/main/res/layout/activity_login.xml

- The UI now responds better to the keyboard.
- Pressing the action button on the keyboard now does what you would expect it to do.
- When pressing the password action button or the login button, a loading bar now appears to indicate that we're logging the user in.

Updated the login page
